rvm:
  - 1.9.2
  - 1.8.7
  - 1.9.3
  - jruby
  - rbx
  - rbx-19mode
  - ree
  - ruby-head

notifications:
  email:
    - sgit-turtle.testudo12@wronghead.com
  irc:
    channels: "irc.freenode.org#toadhopper"